// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: publisher.proto

package publisher

import (
	fmt "fmt"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Publisher service

type PublisherService interface {
	PushTask(ctx context.Context, in *TaskSpec, opts ...client.CallOption) (*emptypb.Empty, error)
}

type publisherService struct {
	c    client.Client
	name string
}

func NewPublisherService(name string, c client.Client) PublisherService {
	return &publisherService{
		c:    c,
		name: name,
	}
}

func (c *publisherService) PushTask(ctx context.Context, in *TaskSpec, opts ...client.CallOption) (*emptypb.Empty, error) {
	req := c.c.NewRequest(c.name, "Publisher.PushTask", in)
	out := new(emptypb.Empty)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Publisher service

type PublisherHandler interface {
	PushTask(context.Context, *TaskSpec, *emptypb.Empty) error
}

func RegisterPublisherHandler(s server.Server, hdlr PublisherHandler, opts ...server.HandlerOption) error {
	type publisher interface {
		PushTask(ctx context.Context, in *TaskSpec, out *emptypb.Empty) error
	}
	type Publisher struct {
		publisher
	}
	h := &publisherHandler{hdlr}
	return s.Handle(s.NewHandler(&Publisher{h}, opts...))
}

type publisherHandler struct {
	PublisherHandler
}

func (h *publisherHandler) PushTask(ctx context.Context, in *TaskSpec, out *emptypb.Empty) error {
	return h.PublisherHandler.PushTask(ctx, in, out)
}
