apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: chaosmetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.6
        command:
          - /usr/local/bin/etcd
          - --data-dir=/etcd-data
          - --name
          - etcd
          - --initial-advertise-peer-urls
          - http://0.0.0.0:2380
          - --listen-peer-urls
          - http://0.0.0.0:2380
          - --advertise-client-urls
          - http://0.0.0.0:2379
          - --listen-client-urls
          - http://0.0.0.0:2379
          - --initial-cluster
          - etcd=http://0.0.0.0:2380
          - --initial-cluster-state
          - new
          - --initial-cluster-token
          - tkn
        ports:
        - containerPort: 2379
        - containerPort: 2380
        volumeMounts:
        - mountPath: /etcd-data
          name: etcd-data
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: chaosmetrics
spec:
  ports:
    - name: client-port  # 为每个端口添加一个名字
      port: 2379
      targetPort: 2379
    - name: peer-port
      port: 2380
      targetPort: 2380
  selector:
    app: etcd