apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  namespace: chaosmetrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: server:local
        command: ["master","--podip=${MY_POD_IP}"]
        ports:
        - containerPort: 8081
        - containerPort: 9091
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: master
  namespace: chaosmetrics
spec:
  ports:
  - port: 8081
    name: http
  - port: 9091
    name: grpc
  selector:
    app: master

