---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: chaosmetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.3
          env:
            - name: MYSQL_DATABASE
              value: "chaosmetrics"
            - name: MYSQL_USER
              value: "chaos"
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: TZ
              value: "Asia/Shanghai"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: chaosmetrics
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: chaosmetrics
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: chaosmetrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi