---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: chaosmetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: shadowhisper/custom-rabbitmq:0.9
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: chaosmetrics
spec:
  ports:
  - port: 5672
    name: amqp-port
    targetPort: 5672
  - port: 15672
    name: management-port
    targetPort: 15672
  selector:
    app: rabbitmq

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: chaosmetrics
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rabbitmq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: chaosmetrics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi