apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  namespace: chaosmetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: server:local
        command: ["router", "--addr=:8080"]
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10