---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  namespace: chaosmetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: shadowhisper/chao_server:v0.92
        command: ["./server"]
        args:
          - "router"
          - "--addr=:8080"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: chaosmetrics
  labels:
    app: router
spec:
  selector:
    app: router
  ports:
    - port: 8080
      name: http
      targetPort: 8080
#      nodePort: 30280
  type: ClusterIP
#  type: NodePort