apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: chaosmetrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: server:local
        command: ["worker", "--podip=$(MY_POD_IP)"]
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: chaos-secrets
                key: API_KEY
          - name: EMAIL_KEY
            valueFrom:
              secretKeyRef:
                name: chaos-secrets
                key: EMAIL_KEY
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
               fieldPath: status.podIP
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: chaosmetrics
spec:
  ports:
  - port: 8082
    name: http
  - port: 9092
    name: grpc
  selector:
    app: worker

