apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: chaosmetrics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: shadowhisper/chao_server:v0.92
        command: [ "./server" ]
        args:
          - "worker"
        env:
          - name: API_KEY
            value: "1xxx"
          - name: EMAIL_KEY
            value: "2xxx"
        ports:
        - containerPort: 8082
        - containerPort: 9092
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: chaosmetrics
spec:
  ports:
  - port: 8082
    name: http
  - port: 9092
    name: grpc
  selector:
    app: worker

