database:
  driver: mysql # 连接驱动
  host: localhost # ip地址
  port: 3306 # 端口
  dbname: chaosmetrics # 数据库
  username: root # 用户名
  password: "123456" # 密码
  charset: utf8mb4 # 字符集
  collation: utf8mb4_unicode_ci # 字符序
  timeout: 10s # 连接超时
  read_timeout: 2s # 读超时
  write_timeout: 2s # 写超时
  parse_time: true # 是否解析时间
  protocol: tcp # 传输协议
  loc: Local # 时区
  conn_max_idle: 10 # 通用配置，连接池最大空闲连接数
  conn_max_open: 100 # 通用配置，连接池最大连接数
  conn_max_lifetime: 1h # 通用配置，连接数最大生命周期

logger:
  maxsize: 500  # 日志的最大大小，以M为单位
  maxbackups: 3  # 保留的旧日志文件的最大数量
  maxage: 30  # 保留旧日志文件的最大天数
  localtime: true
  compress: true