// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/items/item": {
            "get": {
                "description": "请求一个物品详情 @version,lang",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "summary": "请求一个物品详情",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2010",
                        "example": "2010",
                        "description": "The ID of the item",
                        "name": "itemid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "zh_CN",
                        "description": "Language",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "13.8.1",
                        "description": "Version",
                        "name": "version",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/riotmodel.ItemDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Image": {
            "type": "object",
            "properties": {
                "full": {
                    "description": "大图文件名",
                    "type": "string"
                },
                "group": {
                    "description": "图像所属组",
                    "type": "string"
                },
                "h": {
                    "description": "图像高度",
                    "type": "integer"
                },
                "sprite": {
                    "description": "小图文件名",
                    "type": "string"
                },
                "w": {
                    "description": "图像宽度",
                    "type": "integer"
                },
                "x": {
                    "description": "图像 X 坐标",
                    "type": "integer"
                },
                "y": {
                    "description": "图像 Y 坐标",
                    "type": "integer"
                }
            }
        },
        "riotmodel.GoldInfo": {
            "type": "object",
            "properties": {
                "base": {
                    "type": "integer"
                },
                "purchasable": {
                    "type": "boolean"
                },
                "sell": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "riotmodel.ItemDTO": {
            "type": "object",
            "properties": {
                "colloq": {
                    "type": "string"
                },
                "depth": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "from": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "gold": {
                    "$ref": "#/definitions/riotmodel.GoldInfo"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "$ref": "#/definitions/model.Image"
                },
                "into": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "maps": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "name": {
                    "type": "string"
                },
                "plaintext": {
                    "type": "string"
                },
                "stats": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.7",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ChaosMetrics API接口文档",
	Description:      "使用Riot官方API获取数据进行分析、统计项目",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
