basePath: /
definitions:
  anres.ChampionBrief:
    properties:
      avg_damage_dealt:
        description: 场均输出占比 12%
        type: number
      avg_dead_time:
        description: 场均死亡时长
        type: number
      ban_rate:
        description: Ban率
        type: number
      id:
        description: 英雄ID:Aatrox
        type: string
      image:
        allOf:
        - $ref: '#/definitions/model.Image'
        description: basic info
      pick_rate:
        description: 登场率 15%
        type: number
      win_rate:
        description: statistical data
        type: number
    type: object
  model.Image:
    properties:
      full:
        description: 大图文件名
        type: string
      group:
        description: 图像所属组
        type: string
      h:
        description: 图像高度
        type: integer
      sprite:
        description: 小图文件名
        type: string
      w:
        description: 图像宽度
        type: integer
      x:
        description: 图像 X 坐标
        type: integer
      "y":
        description: 图像 Y 坐标
        type: integer
    type: object
  riotmodel.GoldInfo:
    properties:
      base:
        type: integer
      purchasable:
        type: boolean
      sell:
        type: integer
      total:
        type: integer
    type: object
  riotmodel.ItemDTO:
    properties:
      colloq:
        type: string
      depth:
        type: integer
      description:
        type: string
      from:
        items:
          type: string
        type: array
      gold:
        $ref: '#/definitions/riotmodel.GoldInfo'
      id:
        type: string
      image:
        $ref: '#/definitions/model.Image'
      into:
        items:
          type: string
        type: array
      maps:
        additionalProperties:
          type: boolean
        type: object
      name:
        type: string
      plaintext:
        type: string
      stats:
        additionalProperties:
          type: number
        type: object
      tags:
        items:
          type: string
        type: array
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: 使用Riot官方API获取数据进行分析、统计项目
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ChaosMetrics API接口文档
  version: "0.7"
paths:
  /champion/ARAM:
    get:
      consumes:
      - application/json
      description: 请求一个ARAM英雄榜 @version,loc
      parameters:
      - default: na1
        description: region
        in: query
        name: loc
        required: true
        type: string
      - default: 14.1.1
        description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/anres.ChampionBrief'
            type: array
      summary: 请求一个英雄榜
      tags:
      - championrank
  /champion/CLASSIC:
    get:
      consumes:
      - application/json
      description: 请求一个CLASSIC英雄榜 @version,loc
      parameters:
      - default: na1
        description: region
        in: query
        name: loc
        required: true
        type: string
      - default: 14.1.1
        description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/anres.ChampionBrief'
            type: array
      summary: 请求一个英雄榜
      tags:
      - championrank
  /items/item:
    get:
      consumes:
      - application/json
      description: 请求一个物品详情 @version,lang
      parameters:
      - default: "2010"
        description: The ID of the item
        in: query
        name: itemid
        required: true
        type: string
      - default: zh_CN
        description: Language
        in: query
        name: lang
        required: true
        type: string
      - default: 13.8.1
        description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/riotmodel.ItemDTO'
      summary: 请求一个物品详情
      tags:
      - item
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
