basePath: /
definitions:
  anres.ChampionBrief:
    properties:
      avg_damage_dealt:
        description: 场均输出占比 12%
        type: number
      avg_dead_time:
        description: 场均死亡时长
        type: number
      ban_rate:
        description: Ban率
        type: number
      id:
        description: 英雄ID:Aatrox
        type: string
      image:
        allOf:
        - $ref: '#/definitions/model.Image'
        description: basic info
      pick_rate:
        description: 登场率 15%
        type: number
      win_rate:
        description: statistical data
        type: number
    type: object
  anres.ChampionDetail:
    properties:
      avg_damage_dealt:
        description: 场均输出占比 12%
        type: number
      avg_damage_taken:
        description: 场均承伤占比 10%
        type: number
      avg_dead_time:
        description: 场均死亡时长
        type: number
      avg_kda:
        description: 场均KDA 15%
        type: number
      avg_kp:
        description: 场均参团率 10%
        type: number
      avg_time_ccing:
        description: 场均控制时长 5%
        type: number
      avg_vision_score:
        description: 场均视野得分 3%
        type: number
      ban_rate:
        description: Ban率
        type: number
      game_mode:
        description: 游戏模式
        type: string
      id:
        description: 英雄ID:Aatrox
        type: string
      idx:
        description: basic info
        type: string
      image:
        allOf:
        - $ref: '#/definitions/model.Image'
        description: 图像
      item:
        additionalProperties:
          additionalProperties:
            type: integer
          type: object
        description: build winrate
        type: object
      key:
        description: 英雄Key:266
        type: string
      loc:
        description: 对局服务器
        type: string
      name:
        description: 英雄名称:暗裔剑魔
        type: string
      perk:
        additionalProperties:
          type: integer
        type: object
      pick_rate:
        description: 登场率 15%
        type: number
      rank_score:
        description: statistical data
        type: number
      skill:
        additionalProperties:
          type: integer
        type: object
      spell:
        additionalProperties:
          type: integer
        type: object
      title:
        description: 英雄称号:亚托克斯
        type: string
      total_played:
        description: 英雄出场总数
        type: number
      total_win:
        description: 英雄胜利总数
        type: number
      version:
        description: 对局版本
        type: string
      win_rate:
        description: 胜率 30%
        type: number
    type: object
  model.Image:
    properties:
      full:
        description: 大图文件名
        type: string
      group:
        description: 图像所属组
        type: string
      h:
        description: 图像高度
        type: integer
      sprite:
        description: 小图文件名
        type: string
      w:
        description: 图像宽度
        type: integer
      x:
        description: 图像 X 坐标
        type: integer
      "y":
        description: 图像 Y 坐标
        type: integer
    type: object
  response.EntryDTO:
    properties:
      leaguePoints:
        description: 段位积分
        type: integer
      losses:
        description: 负场次数（召唤师峡谷）
        type: integer
      queueType:
        description: 排位类型
        type: string
      rank:
        description: 段位
        type: string
      tier:
        description: 段位
        type: string
      wins:
        description: 胜场次数（召唤师峡谷）
        type: integer
    type: object
  response.MatchDTO:
    properties:
      gameCreation:
        type: integer
      gameDuration:
        type: integer
      matchID:
        type: string
      participants:
        items:
          $ref: '#/definitions/response.Participant'
        type: array
      queueId:
        description: 队列ID
        type: integer
    type: object
  response.Participant:
    properties:
      assists:
        description: 助攻数
        type: integer
      championName:
        description: 英雄名称
        type: string
      damageDealt:
        description: 造成伤害
        type: integer
      damageToken:
        description: 承受伤害
        type: integer
      deaths:
        description: 死亡数
        type: integer
      item0:
        description: 物品0
        type: integer
      item1:
        description: 物品1
        type: integer
      item2:
        description: 物品2
        type: integer
      item3:
        description: 物品3
        type: integer
      item4:
        description: 物品4
        type: integer
      item5:
        description: 物品5
        type: integer
      item6:
        description: 物品6 (饰品)
        type: integer
      itemBuild:
        description: 出装构筑
        type: string
      kda:
        description: KDA
        type: number
      kills:
        description: 击杀数
        type: integer
      kp:
        description: 击杀参与率
        type: number
      pentaKills:
        description: 五杀数
        type: integer
      perkBuild:
        description: 符文构筑
        type: string
      quadraKills:
        description: 四杀数
        type: integer
      skillBuild:
        description: 技能构筑
        type: string
      summoner1Id:
        description: 召唤师技能1ID
        type: integer
      summoner2Id:
        description: 召唤师技能2ID
        type: integer
      summonerName:
        description: 召唤师名称
        type: string
      teamId:
        description: 队伍ID
        type: integer
      tripleKills:
        description: 三杀数
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.SummonerDTO:
    properties:
      flexEntry:
        $ref: '#/definitions/response.EntryDTO'
      loc:
        type: string
      matches:
        items:
          $ref: '#/definitions/response.MatchDTO'
        type: array
      name:
        type: string
      profileIconID:
        type: integer
      soloEntry:
        $ref: '#/definitions/response.EntryDTO'
      summonerLevel:
        type: integer
    type: object
  riotmodel.GoldInfo:
    properties:
      base:
        type: integer
      purchasable:
        type: boolean
      sell:
        type: integer
      total:
        type: integer
    type: object
  riotmodel.ItemDTO:
    properties:
      colloq:
        type: string
      depth:
        type: integer
      description:
        type: string
      from:
        items:
          type: string
        type: array
      gold:
        $ref: '#/definitions/riotmodel.GoldInfo'
      id:
        type: string
      image:
        $ref: '#/definitions/model.Image'
      into:
        items:
          type: string
        type: array
      maps:
        additionalProperties:
          type: boolean
        type: object
      name:
        type: string
      plaintext:
        type: string
      stats:
        additionalProperties:
          type: number
        type: object
      tags:
        items:
          type: string
        type: array
    type: object
  user.loginParam:
    properties:
      password:
        example: "123456"
        minLength: 6
        type: string
      username:
        example: snoop
        type: string
    required:
    - password
    - username
    type: object
  user.registerParam:
    properties:
      email:
        example: snoop@dogg.com
        minLength: 6
        type: string
      password:
        example: "123456"
        minLength: 6
        type: string
      username:
        example: snoop
        type: string
    required:
    - email
    - password
    - username
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: 使用Riot官方API获取数据进行分析、统计项目
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ChaosMetrics API接口文档
  version: "0.8"
paths:
  /ARAM:
    get:
      consumes:
      - application/json
      description: query @version,loc
      parameters:
      - default: na1
        description: Region
        in: query
        name: loc
        required: true
        type: string
      - default: 14.1.1
        description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/anres.ChampionBrief'
                  type: array
              type: object
      summary: 请求一个ARAM英雄榜
      tags:
      - Champion Rank
  /CLASSIC:
    get:
      consumes:
      - application/json
      description: query @version,loc
      parameters:
      - default: na1
        description: Region
        in: query
        name: loc
        required: true
        type: string
      - default: 14.1.1
        description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/anres.ChampionBrief'
            type: array
      summary: 请求一个CLASSIC英雄榜
      tags:
      - Champion Rank
  /champion:
    get:
      consumes:
      - application/json
      description: query @name,version,loc,mode
      parameters:
      - default: na1
        description: Region
        in: query
        name: loc
        required: true
        type: string
      - default: CLASSIC
        description: Game mode
        in: query
        name: mode
        required: true
        type: string
      - default: Ahri
        description: Champion name
        in: query
        name: name
        required: true
        type: string
      - default: 14.1.1
        description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/anres.ChampionDetail'
              type: object
      summary: 请求一个英雄详情
      tags:
      - Champion Detail
  /item:
    get:
      consumes:
      - application/json
      description: query @version,lang
      parameters:
      - default: "2010"
        description: The ID of the item
        in: query
        name: itemid
        required: true
        type: string
      - default: zh_CN
        description: Language
        in: query
        name: lang
        required: true
        type: string
      - default: 13.8.1
        description: Version
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/riotmodel.ItemDTO'
              type: object
      summary: 请求一个物品详情
      tags:
      - Item
  /summoner:
    get:
      consumes:
      - application/json
      description: query @name,loc
      parameters:
      - default: na1
        description: Region
        in: query
        name: loc
        required: true
        type: string
      - default: pwVx hysamirapwd
        description: Summoner name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.SummonerDTO'
              type: object
      summary: 请求一个召唤师详情
      tags:
      - Summoner Detail
  /user/login:
    post:
      consumes:
      - application/json
      description: login @usrname,passwd
      parameters:
      - description: login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.loginParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 用户登陆
      tags:
      - User Service
  /user/logout:
    get:
      consumes:
      - application/json
      description: login @usrname,passwd
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 用户登陆
      tags:
      - User Service
  /user/register:
    post:
      consumes:
      - application/json
      description: register @usrname,passwd,email
      parameters:
      - description: Register a new user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.registerParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 注册一个新用户
      tags:
      - User Service
  /user/verify:
    get:
      consumes:
      - application/json
      description: query @token
      parameters:
      - in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 验证注册信息
      tags:
      - User Service
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
