env: dev  # 环境(test|dev|product)

database:
  driver: mysql            # 连接驱动
  host: localhost          # 数据库服务器的 IP 地址
  port: 3306               # 数据库服务器的端口号
  dbname: chaosmetrics     # 数据库名称
  username: root           # 数据库用户名
  password: "123456"       # 数据库密码
  charset: utf8mb4         # 字符集
  collation: utf8mb4_unicode_ci   # 字符序
  timeout: 10s             # 连接超时时间
  read_timeout: 2s         # 读超时时间
  write_timeout: 2s        # 写超时时间
  parse_time: true         # 是否解析时间
  protocol: tcp            # 传输协议
  loc: Local               # 时区
  conn_max_idle: 10        # 连接池最大空闲连接数
  conn_max_open: 100       # 连接池最大连接数
  conn_max_lifetime: 1h    # 连接的最大生命周期

logger:
  maxsize: 500             # 日志文件的最大大小，以兆字节（M）为单位
  maxbackups: 3            # 保留的旧日志文件的最大数量
  maxage: 30               # 保留旧日志文件的最大天数
  localtime: true          # 是否使用本地时间记录日志
  compress: true           # 是否压缩旧的日志文件

fetcher:
  timeout: 15 # 连接超时时间
  header:
    user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36  # 用户代理
    accept_language: zh-CN,zh;q=0.9,ja-JP;q=0.8,ja;q=0.7  # 接受的语言
    accept_charset: application/x-www-form-urlencoded; charset=UTF-8  # 接受的字符集
    origin: https://developer.riotgames.com  # 请求来源
  rate_limiter:
    each_sec: 20  # 每秒允许的 API 请求次数限制
    each_2min: 98  # 每两分钟允许的 API 请求次数限制

redis:
  host: localhost # ip地址
  port: 6379 # 端口
  db: 0 #db
  username: testman # 用户名
  password: "" # 密码
  timeout: 10s # 连接超时
  read_timeout: 2s # 读超时
  write_timeout: 2s # 写超时
  conn_min_idle: 10 # 连接池最小空闲连接数
  conn_max_open: 20 # 连接池最大连接数
  conn_max_lifetime: 1h # 连接数最大生命周期
  conn_max_idletime: 1h # 连接数空闲时长

system:
  registry_address: "localhost:2379"
  register_ttl: 60
  register_interval: 15
  client_timeout: 10
  router_prefix: ""

jwt:
  signing_key: open sesame
  expires_time: 1h
  buffer_time: 15m
  issuer: chaos