// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Messager_AddResource_FullMethodName    = "/Messager/AddResource"
	Messager_DeleteResource_FullMethodName = "/Messager/DeleteResource"
)

// MessagerClient is the client API for Messager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessagerClient interface {
	AddResource(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*NodeSpec, error)
	DeleteResource(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type messagerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagerClient(cc grpc.ClientConnInterface) MessagerClient {
	return &messagerClient{cc}
}

func (c *messagerClient) AddResource(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*NodeSpec, error) {
	out := new(NodeSpec)
	err := c.cc.Invoke(ctx, Messager_AddResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagerClient) DeleteResource(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Messager_DeleteResource_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagerServer is the server API for Messager service.
// All implementations must embed UnimplementedMessagerServer
// for forward compatibility
type MessagerServer interface {
	AddResource(context.Context, *TaskSpec) (*NodeSpec, error)
	DeleteResource(context.Context, *TaskSpec) (*emptypb.Empty, error)
	mustEmbedUnimplementedMessagerServer()
}

// UnimplementedMessagerServer must be embedded to have forward compatible implementations.
type UnimplementedMessagerServer struct {
}

func (UnimplementedMessagerServer) AddResource(context.Context, *TaskSpec) (*NodeSpec, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddResource not implemented")
}
func (UnimplementedMessagerServer) DeleteResource(context.Context, *TaskSpec) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedMessagerServer) mustEmbedUnimplementedMessagerServer() {}

// UnsafeMessagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessagerServer will
// result in compilation errors.
type UnsafeMessagerServer interface {
	mustEmbedUnimplementedMessagerServer()
}

func RegisterMessagerServer(s grpc.ServiceRegistrar, srv MessagerServer) {
	s.RegisterService(&Messager_ServiceDesc, srv)
}

func _Messager_AddResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).AddResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messager_AddResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).AddResource(ctx, req.(*TaskSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messager_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Messager_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).DeleteResource(ctx, req.(*TaskSpec))
	}
	return interceptor(ctx, in, info, handler)
}

// Messager_ServiceDesc is the grpc.ServiceDesc for Messager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Messager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Messager",
	HandlerType: (*MessagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddResource",
			Handler:    _Messager_AddResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _Messager_DeleteResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
